### ISSUE TITLE
Class for Flex Properties

### ISSUE THREAD

**Issue by cyouh95** [Kishgla/TeaCozy#2]
Instead of having to specify properties such as `display: flex;` for multiple elements, you could create another class and assign it to all elements you want to style with these properties. For example:

```css
.flex-container {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}
```

https://github.com/Kishgla/TeaCozy/blob/master/css/style.css
